'use client';

import React, { useState, useEffect } from 'react';
import { Network, GitBranch, Activity, FileCode, AlertCircle } from 'lucide-react';
import MermaidChart from '../MermaidChart';

interface MindMapViewProps {
  // This component now needs the FILE CONTENT, not the diagram code,
  // because it will send this content to the AI to be analyzed.
  selectedFileContent: string | null;
  // Optional: Trigger generation externally
  triggerGeneration?: { type: 'flowchart' | 'mindmap' | null; timestamp?: number };
}

export default function MindMapView({ selectedFileContent, triggerGeneration }: MindMapViewProps) {
  const [mermaidCode, setMermaidCode] = useState<string>('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeView, setActiveView] = useState<'flowchart' | 'mindmap' | null>(null);

  // Reset state when a new file is selected
  useEffect(() => {
    setMermaidCode('');
    setError(null);
    setActiveView(null);
  }, [selectedFileContent]);

  // Function to call your AI Backend
  const handleGenerate = async (type: 'flowchart' | 'mindmap') => {
    if (!selectedFileContent) return;

    setIsLoading(true);
    setError(null);
    setActiveView(type);
    setMermaidCode(''); // Clear previous chart

    try {
      const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:4000';
      const response = await fetch(`${API_BASE_URL}/api/ai/generate-diagram`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          codeContent: selectedFileContent,
          diagramType: type,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || errorData.details || `HTTP ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();

      if (data.success && data.mermaidCode) {
        setMermaidCode(data.mermaidCode);
      } else {
        throw new Error(data.error || 'No diagram generated by the AI.');
      }
    } catch (err: any) {
      console.error('[MindMapView] Error generating diagram:', err);
      setError(err.message || 'Failed to generate diagram. Is the server running?');
    } finally {
      setIsLoading(false);
    }
  };

  // Handle external trigger for generation
  useEffect(() => {
    if (triggerGeneration?.type && selectedFileContent && triggerGeneration.timestamp) {
      handleGenerate(triggerGeneration.type);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [triggerGeneration?.timestamp]);

  return (
    <div className="h-full flex flex-col bg-[#252526] overflow-hidden border-l border-[#3e3e42]">
      <style jsx>{`
        .mindmap-header {
          padding: 10px 16px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
          background: #252526;
          display: flex;
          flex-direction: column;
          gap: 12px;
        }
        .header-title {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 11px;
          font-weight: 600;
          color: #9cdcfe;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .mindmap-canvas {
          flex: 1;
          overflow: hidden; /* MermaidChart handles scrolling */
          padding: 0;
          background: #1e1e1e;
          position: relative;
        }
        .placeholder-container {
          position: absolute;
          inset: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          color: #6b7280;
          gap: 12px;
          text-align: center;
          padding: 20px;
        }
      `}</style>

      {/* --- HEADER SECTION --- */}
      <div className="mindmap-header">
        <div className="header-title">
          <Network size={14} />
          <span>Code Visualization</span>
        </div>

        {/* Control Buttons */}
        <div className="flex gap-2">
          <button
            onClick={() => handleGenerate('flowchart')}
            disabled={!selectedFileContent || isLoading}
            className={`flex-1 flex items-center justify-center gap-2 px-3 py-1.5 rounded text-xs font-medium transition-all
              ${activeView === 'flowchart' ? 'bg-[#007acc] text-white' : 'bg-[#3c3c3c] hover:bg-[#4c4c4c] text-gray-300'}
              ${(!selectedFileContent || isLoading) && 'opacity-50 cursor-not-allowed'}
            `}
          >
            <GitBranch size={14} />
            Flowchart
          </button>

          <button
            onClick={() => handleGenerate('mindmap')}
            disabled={!selectedFileContent || isLoading}
            className={`flex-1 flex items-center justify-center gap-2 px-3 py-1.5 rounded text-xs font-medium transition-all
              ${activeView === 'mindmap' ? 'bg-[#007acc] text-white' : 'bg-[#3c3c3c] hover:bg-[#4c4c4c] text-gray-300'}
              ${(!selectedFileContent || isLoading) && 'opacity-50 cursor-not-allowed'}
            `}
          >
            <Activity size={14} />
            Mind Map
          </button>
        </div>
      </div>

      {/* --- CANVAS SECTION --- */}
      <div className="mindmap-canvas">
        {isLoading ? (
          <div className="placeholder-container">
            <div className="animate-spin h-6 w-6 border-2 border-[#007acc] border-t-transparent rounded-full mb-2"></div>
            <span className="text-xs text-gray-400">AI is analyzing structure...</span>
          </div>
        ) : error ? (
          <div className="placeholder-container text-red-400">
            <AlertCircle size={32} />
            <span className="text-sm font-medium">Generation Failed</span>
            <span className="text-xs opacity-70">{error}</span>
          </div>
        ) : mermaidCode ? (
          // RENDER SUCCESS
          <div className="w-full h-full p-4 overflow-auto">
            <MermaidChart chart={mermaidCode} />
          </div>
        ) : (
          // INITIAL STATE
          <div className="placeholder-container opacity-50">
            <FileCode size={40} />
            <div>
              <p className="text-sm font-medium text-gray-400">No Visualization</p>
              <p className="text-xs text-gray-600 mt-1">
                {!selectedFileContent 
                  ? "Select a file to enable controls" 
                  : "Click a button above to generate"}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}