'use client';

import React, { useEffect, useState } from 'react';
import { Activity, AlertCircle, FileCode, GitBranch, Network } from 'lucide-react';
import MermaidChart from '../MermaidChart';

interface MindMapViewProps {
  selectedFileContent: string | null;
  triggerGeneration?: { type: 'flowchart' | 'mindmap' | null; timestamp?: number };
}

export default function MindMapView({ selectedFileContent, triggerGeneration }: MindMapViewProps) {
  const [mermaidCode, setMermaidCode] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeView, setActiveView] = useState<'flowchart' | 'mindmap' | null>(null);

  useEffect(() => {
    setMermaidCode('');
    setError(null);
    setActiveView(null);
  }, [selectedFileContent]);

  const handleGenerate = async (type: 'flowchart' | 'mindmap') => {
    if (!selectedFileContent) return;

    setIsLoading(true);
    setError(null);
    setActiveView(type);
    setMermaidCode('');

    try {
      const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:4000';
      const response = await fetch(`${API_BASE_URL}/api/ai/generate-diagram`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          codeContent: selectedFileContent,
          diagramType: type,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error || errorData.details || `HTTP ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();
      if (data.success && data.mermaidCode) {
        setMermaidCode(data.mermaidCode);
      } else {
        throw new Error(data.error || 'No diagram generated by the AI.');
      }
    } catch (err: unknown) {
      console.error('[MindMapView] Error generating diagram:', err);
      setError(err instanceof Error ? err.message : 'Failed to generate diagram. Is the server running?');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (triggerGeneration?.type && selectedFileContent && triggerGeneration.timestamp) {
      handleGenerate(triggerGeneration.type);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [triggerGeneration?.timestamp]);

  return (
    <div className="h-full flex flex-col cm-sidebar overflow-hidden">
      <div className="p-3 border-b border-[var(--cm-border)] bg-[rgba(2,6,23,0.42)]">
        <div className="flex items-center gap-2 mb-2">
          <Network size={14} className="text-[var(--cm-primary)]" />
          <span className="text-[11px] uppercase tracking-[0.12em] font-semibold text-[var(--cm-text-muted)]">
            Code Visualization
          </span>
        </div>
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => handleGenerate('flowchart')}
            disabled={!selectedFileContent || isLoading}
            className={`h-8 rounded-md text-xs font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeView === 'flowchart'
                ? 'cm-btn-primary text-white'
                : 'cm-btn-ghost'
            } ${(!selectedFileContent || isLoading) ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            <GitBranch size={13} />
            Flowchart
          </button>
          <button
            onClick={() => handleGenerate('mindmap')}
            disabled={!selectedFileContent || isLoading}
            className={`h-8 rounded-md text-xs font-medium flex items-center justify-center gap-1.5 transition-all ${
              activeView === 'mindmap'
                ? 'cm-btn-primary text-white'
                : 'cm-btn-ghost'
            } ${(!selectedFileContent || isLoading) ? 'opacity-50 cursor-not-allowed' : ''}`}
          >
            <Activity size={13} />
            Mind Map
          </button>
        </div>
      </div>

      <div className="flex-1 relative overflow-hidden bg-[rgba(2,6,23,0.45)]">
        {isLoading ? (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 text-[var(--cm-text-muted)]">
            <div className="h-7 w-7 rounded-full border-2 border-[var(--cm-primary)] border-t-transparent animate-spin" />
            <span className="text-xs">AI is analyzing structure...</span>
          </div>
        ) : error ? (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 px-6 text-center">
            <AlertCircle size={30} className="text-red-400" />
            <span className="text-sm text-red-300">Generation failed</span>
            <span className="text-xs text-red-300/80">{error}</span>
          </div>
        ) : mermaidCode ? (
          <div className="h-full w-full overflow-auto p-4">
            <MermaidChart chart={mermaidCode} />
          </div>
        ) : (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 px-6 text-center text-[var(--cm-text-muted)]">
            <FileCode size={38} className="opacity-45" />
            <p className="text-sm">
              {!selectedFileContent ? 'Select a file to enable controls' : 'Click a button above to generate'}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
